# Generated by Django 4.0 on 2021-12-17 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phongmach', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='unit_price_medicine',
            field=models.FloatField(default=20000),
            preserve_default=False,
        ),
    ]
