# Generated by Django 4.0 on 2021-12-17 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phongmach', '0002_medicine_unit_price_medicine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='unit_price_medicine',
            field=models.FloatField(default=None),
        ),
    ]
