# Generated by Django 4.0 on 2021-12-20 02:18

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phongmach', '0003_alter_medicine_unit_price_medicine'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': [builtins.id]},
        ),
        migrations.AlterField(
            model_name='medicine',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
