# Generated by Django 4.0 on 2021-12-20 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phongmach', '0004_alter_category_options_alter_medicine_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
    ]
