# Generated by Django 3.2.10 on 2021-12-25 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phongmach', '0011_auto_20211225_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='bill',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='prescription_detail',
            name='name_medicine',
        ),
        migrations.RemoveField(
            model_name='prescription_detail',
            name='prescription',
        ),
        migrations.DeleteModel(
            name='Bill',
        ),
        migrations.DeleteModel(
            name='Prescription',
        ),
        migrations.DeleteModel(
            name='Prescription_Detail',
        ),
    ]
