# Generated by Django 3.2.10 on 2021-12-27 04:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phongmach', '0013_bill_prescription_prescription_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medical_Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('unit_price', models.FloatField(default=None)),
            ],
        ),
        migrations.AddField(
            model_name='bill',
            name='medical_expenses',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bill',
            name='total',
            field=models.FloatField(default='0'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default=None, null=True, upload_to='uploads/%Y/%m'),
        ),
    ]
