# Generated by Django 3.2.10 on 2021-12-27 05:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phongmach', '0014_auto_20211227_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duty',
            name='duty_day',
        ),
        migrations.RemoveField(
            model_name='duty',
            name='staff',
        ),
        migrations.AddField(
            model_name='duty',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Duty_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duty_day', models.DateField(default=None)),
                ('Duty', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='phongmach.duty')),
            ],
        ),
    ]
