# Generated by Django 3.2.10 on 2021-12-27 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phongmach', '0015_auto_20211227_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='duty',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
