# Generated by Django 3.2.10 on 2021-12-27 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phongmach', '0016_duty_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='duty_details',
            old_name='Duty',
            new_name='duty',
        ),
    ]
