# Generated by Django 3.2.10 on 2021-12-27 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phongmach', '0017_rename_duty_duty_details_duty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='bill',
        ),
        migrations.AddField(
            model_name='bill',
            name='prescription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescription', to='phongmach.prescription'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='medical_expenses',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to=settings.AUTH_USER_MODEL),
        ),
    ]
