# Generated by Django 3.2.10 on 2021-12-28 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phongmach', '0018_auto_20211227_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medical_examination',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
