# Generated by Django 3.2.10 on 2021-12-28 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phongmach', '0019_auto_20211228_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription_detail',
            name='name_medicine',
            field=models.ManyToManyField(to='phongmach.Medicine'),
        ),
    ]
