# Generated by Django 3.2.10 on 2021-12-28 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phongmach', '0022_alter_bill_medical_expenses'),
    ]

    operations = [
        migrations.AddField(
            model_name='medical_examination',
            name='subject',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='diagnose',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='medical_examination',
            name='register_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
