# Generated by Django 3.2.10 on 2021-12-28 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phongmach', '0023_auto_20211228_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case_record',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='case_record',
            name='diagnose',
        ),
        migrations.RemoveField(
            model_name='case_record',
            name='patient',
        ),
        migrations.AddField(
            model_name='case_record',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='diagnose',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='phongmach.case_record'),
        ),
    ]
