# Generated by Django 3.2.10 on 2021-12-28 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phongmach', '0024_auto_20211228_1951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case_record',
            old_name='name',
            new_name='diagnose',
        ),
    ]
