# Generated by Django 3.2.10 on 2021-12-28 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phongmach', '0025_rename_name_case_record_diagnose'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='total_money',
        ),
    ]
