# Generated by Django 3.2.10 on 2021-12-28 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phongmach', '0026_remove_prescription_total_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=1981),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prescription',
            name='diagnose',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.DeleteModel(
            name='Case_Record',
        ),
    ]
