# Generated by Django 3.2.10 on 2021-12-28 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phongmach', '0027_auto_20211228_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='created_date',
        ),
    ]
