# Generated by Django 3.2.10 on 2021-12-28 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phongmach', '0028_remove_prescription_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default='2021-10-30 00:00:00'),
            preserve_default=False,
        ),
    ]
