# Generated by Django 3.2.10 on 2021-12-28 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phongmach', '0030_case_record'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Case_Record',
        ),
    ]
