# Generated by Django 3.2.10 on 2021-12-28 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phongmach', '0031_delete_case_record'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='prescription_detail',
            name='name_medicine',
        ),
        migrations.RemoveField(
            model_name='prescription_detail',
            name='prescription',
        ),
        migrations.DeleteModel(
            name='Bill',
        ),
        migrations.DeleteModel(
            name='Prescription',
        ),
        migrations.DeleteModel(
            name='Prescription_Detail',
        ),
    ]
