# Generated by Django 3.2.10 on 2021-12-28 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phongmach', '0035_bill_prescription_prescription_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medical_examination',
            name='register_date',
            field=models.DateField(default=None),
        ),
    ]
