# Generated by Django 3.2.10 on 2021-12-28 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phongmach', '0036_alter_medical_examination_register_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription_detail',
            name='unit_price',
        ),
    ]
